### ISSUE TITLE
 The ESM module loader is experimental.

### ISSUE THREAD

**Issue by sonatina3** [LeeHyKu/Altiora-Keqing#2]
실행시 아래와 같은 오류 발생

``` import * as Auth from "./Auth.json";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

package.json 에 "type" : "module" 추가 
실행시켰더니 아래와 같은 오류 발생

``` (node:30772) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users/-----\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing' imported from C:\Users\----\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\app.ts
    at finalizeResolution (internal/modules/esm/resolve.js:259:11)
    at moduleResolve (internal/modules/esm/resolve.js:636:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
구글링 해보니, "type" : "module" 를 제거하라함, 제거시 1번째 오류 발생

**Comment by LeeHyKu** [comment]
노드 버전
타입스트립트 버전
node-kakao 버전 적어주세요

**Comment by LeeHyKu** [comment]
노드는 14.X 버전(14.12.0 이상 권장)
타입스트립트는 4.X 버전
node-kakao는 3.1.X 버전이여야 합니다

**Comment by LeeHyKu** [comment]
혹시 `npm run start`나 `bash Keqing.sh`로 실행하셨나요? 지금 보니까 제가 뭐 하나 잘못 넣었었네요
수정한거 올렸는데 에러 계속 뜨는지 알려주세요

**Comment by sonatina3** [comment]
node.js : 14.14.9
typescript : 4.1.2
node-kakao : 3.1.2

npm run start 로 실행하였습니다.
아래와 같은 오류 발생
```
C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main>npm run start

> keqing@1.1.0 start C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main
> node .

internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module 'C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\app.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at resolveMainPath (internal/modules/run_main.js:12:25)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\7kkle\\Downloads\\Altiora-Keqing-main\\Altiora-Keqing-main\\package.json',
  requestPath: 'C:\\Users\\7kkle\\Downloads\\Altiora-Keqing-main\\Altiora-Keqing-main'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keqing@1.1.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keqing@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\7kkle\AppData\Roaming\npm-cache\_logs\2021-03-01T10_22_08_559Z-debug.log
```

**Comment by LeeHyKu** [comment]
```
npm i typescript -g
tsc
```
하신 뒤에 실행해보시겠어요?

**Comment by sonatina3** [comment]
``` keqing@1.1.0 start C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main
> node . "run"

[중요]오후 7:41:33 Ignition Sequence Starts
[심각]오후 7:41:34 MongoParseError:Invalid connection string
    at connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\operations\connect.js:282:3)
    at C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:224:5
    at maybePromise (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\utils.js:665:3)
    at MongoClient.connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:220:10)
    at Function.MongoClient.connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:443:22)
    at Citius.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Citius\Citius.js:31:62)
    at Keqing.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing.js:61:31)
    at Object.<anonymous> (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\app.js:54:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
[심각]오후 7:41:34 TypeError:Cannot read property 'collection' of undefined
    at Lamy.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Lamy\Lamy.js:26:39)
    at Keqing.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing.js:62:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by LeeHyKu** [comment]
https://www.mongodb.com/
설치해주세요

**Comment by LeeHyKu** [comment]
추가로 Auth.json에 정보 입력해주세요

**Comment by LeeHyKu** [comment]
app.ts, Auth.json에 모든 정보 입력하셨나 확인해주세요
app.ts에 있는 정보는 수정한 뒤에 `tsc` 명령어 돌려주세요

**Comment by sonatina3** [comment]
app.ts Auth.json 에 모든 정보 입력하였습니다.
``` C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main>tsc
error TS5023: Unknown compiler option 'lib'.
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'resolveJsonModule'.
error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.

C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main>npm run start

> keqing@1.1.0 start C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main
> node .

[중요]오후 10:21:07 Ignition Sequence Starts
[심각]오후 10:21:07 MongoParseError:Invalid connection string
    at connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\operations\connect.js:282:3)
    at C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:224:5
    at maybePromise (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\utils.js:665:3)
    at MongoClient.connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:220:10)
    at Function.MongoClient.connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:443:22)
    at Citius.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Citius\Citius.js:31:62)
    at Keqing.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing.js:61:31)
    at Object.<anonymous> (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\app.js:54:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
[심각]오후 10:21:07 TypeError:Cannot read property 'collection' of undefined
    at Lamy.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Lamy\Lamy.js:26:39)
    at Keqing.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing.js:62:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) ```

**Comment by LeeHyKu** [comment]
app.ts

34~38줄 올려주세요

**Comment by sonatina3** [comment]
DBPath: 'mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb',
		DBName: 'admin',
		Tables: {
			Channel: '[Test Room]',
			User: 'Bot Manager'

**Comment by LeeHyKu** [comment]
우선 뒤에 쿼리 제외하고 `mongodb://localhost:27017`로 해보세요
DB 원하시는 이름으로 새로 생성하시고, Channel, User는 활동할 채널, 유저가 아니라 테이블 이름이므로 `Channel`, `User`로 설정하시는걸 권장드립니다

**Comment by sonatina3** [comment]
정말 죄송하지만 말씀해주신대로 하였지만,  아래와 같은 오류가 계속 발생합니다

app.ts 34-37
``` itius: {
		DBPath: 'mongodb://localhost:27017',
		DBName: 'bot_db',
		Tables: {
			Channel: 'Channel',
			User: 'User'
			```
error
```
C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main>tsc
error TS5023: Unknown compiler option 'lib'.
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'resolveJsonModule'.
error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.

C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main>npm run start

> keqing@1.1.0 start C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main
> node .

[중요]오후 10:58:32 Ignition Sequence Starts
[심각]오후 10:58:32 MongoParseError:Invalid connection string
    at connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\operations\connect.js:282:3)
    at C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:224:5
    at maybePromise (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\utils.js:665:3)
    at MongoClient.connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:220:10)
    at Function.MongoClient.connect (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\node_modules\mongodb\lib\mongo_client.js:443:22)
    at Citius.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Citius\Citius.js:31:62)
    at Keqing.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing.js:61:31)
    at Object.<anonymous> (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\app.js:54:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
[심각]오후 10:58:32 TypeError:Cannot read property 'collection' of undefined
    at Lamy.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Lamy\Lamy.js:26:39)
    at Keqing.Ignition (C:\Users\7kkle\Downloads\Altiora-Keqing-main\Altiora-Keqing-main\src\Core\Keqing.js:62:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    
    ```

**Comment by LeeHyKu** [comment]
디스코드 HKLee#6974로 연락주세요
